// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/series": {
            "post": {
                "description": "Crea una nueva serie",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "series"
                ],
                "summary": "Crear serie",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Título",
                        "name": "titulo",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sinopsis",
                        "name": "sinopsis",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "País de origen",
                        "name": "pais_origen",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Género principal",
                        "name": "genero_principal",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Número de episodios",
                        "name": "episodios",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Imagen de portada",
                        "name": "imagen",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/series/{id}": {
            "delete": {
                "tags": [
                    "series"
                ],
                "summary": "Eliminar serie",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la serie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/series/{id}/ratings": {
            "get": {
                "description": "Retorna el promedio de ratings de una serie",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ratings"
                ],
                "summary": "Obtener rating promedio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la serie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Series Tracker API",
	Description:      "API para gestionar series y ratings",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
