/*Limpieza de tablas*/

DROP TABLE IF EXISTS rating;
DROP TABLE IF EXISTS series;

/*Creación de tablas*/

CREATE TABLE IF NOT EXISTS series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    sinopsis TEXT NOT NULL,
    episodios INT NOT NULL CHECK (episodios > 0),
    pais_origen VARCHAR(50) NOT NULL,
    genero_principal VARCHAR(50) NOT NULL,
    portada_url TEXT NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ratings(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serie_id BIGINT NOT NULL REFERENCES series(id) ON DELETE CASCADE,
    puntaje INT NOT NULL CHECK (puntaje BETWEEN 1 AND 5),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

/*Creación de indices*/
CREATE INDEX idx_ratings_serie_id ON ratings(serie_id);